---

- name: Include os specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include RedHat specific tasks
  include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include Debian specific tasks
  include: Debian.yml
  when: ansible_os_family == 'Debian'
